[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/hello-world"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/hello-world/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/hello-world/"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-sitemap.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/author/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/category/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/tag/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/feed"
  to = "/"
  status = 301

[[redirects]]
  from = "/feed/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/page/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-login.php"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-admin"
  to = "/"
  status = 301

[[redirects]]
  from = "/wp-admin/*"
  to = "/"
  status = 301
